### ISSUE TITLE
Static site duplicate snapshot errors

### ISSUE THREAD

**Issue by LukyVj** [percy/percy-agent#477]
Hello, and thank you for creating this plugin. 
We need to use it at Algolia, and everything went smoothly until the code reaches CircleCI.

For a reason, I errors like this for every single page: 
```
[percy] serving static site at http://localhost:5339/
[percy] snapshot taken: '/404.html'
[percy] StatusCodeError 400 - {"errors":[{"status":"bad_request"},{"source":{"pointer":"/data/attributes/base"},"detail":"The name of each snapshot must be unique, and this name already exists in the build: '/404.html' -- You can fix this by passing a 'name' param when creating the snapshot. See the docs for more info on identifying snapshots for your specific client: https://percy.io/docs"}]} | Wed Mar 04 2020 14:30:35 GMT+0000 (Coordinated Universal Time)
``` 

From my understanding, at our user level, it is impossible to "pass a 'name' param" unless we fork the plugin? 

Would you be willing to look into it? Or have you already had such experiences with this error? 

Thank you!

**Comment by LukyVj** [comment]
Hey @Robdel12 ! Sorry for the delay, I was somewhat off for a few days. 

So, I'm no expert in this whole percy topic, but I believe there is a default value for these globs. 

It could indeed be a parallel issue, as I'm not familiar with this, I know I enabled some on Circle, so it could be the issue. I'm going to try to remove it and see if it works. 

Anyway, here is our config file: 
( due to some potentially sensible information, I'll share the needed subset of config ) 

*Circle config*:
```
defaults: &defaults
  working_directory: ~/AlgoliaWeb_static-react
  parallelism: 3
  docker:
    - image: circleci/node:11.12.0

[...]

  test_visual:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          command: export PERCY_TOKEN=$PERCY_TOKEN
      - run:
          name: Install Headless Chrome dependencies
          command: |
            sudo apt-get install -yq \
            gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - run:
          command: yarn build

workflows:
  ci:
    jobs:
      - test_lint
      - test_e2e
      - test_visual
``` 

*Percy config*: 
```
version: 1
snapshot:
  widths: [1280]
  min-height: 1224
  percy-css: |
    iframe,
    .cookies-eu,
    #drift-widget-container,
    foo {
      display: none;
    }
agent:
  asset-discovery:
    network-idle-timeout: 500 # .ms
    page-pool-size-min: 5 # pages
    page-pool-size-max: 20 # pages

```

As I said, I'm going to try to run it with the parallel disabled and see if it works.
