### ISSUE TITLE
Orb finalizes successfully, but Percy reports an error

### ISSUE THREAD

**Issue by rbren** [percy/percy-agent#630]
<img width="665" alt="Screen Shot 2021-06-08 at 4 21 53 PM" src="https://user-images.githubusercontent.com/7611973/121252130-a8950780-c875-11eb-9f68-70b44a1a6c99.png">

<img width="996" alt="Screen Shot 2021-06-08 at 4 22 14 PM" src="https://user-images.githubusercontent.com/7611973/121252183-b6e32380-c875-11eb-8876-c6fae6450a7a.png">

Any ideas what I'm doing wrong?

More details:
* Using cypress with @percy/cypress
* orb version 0.1.3

here's the relevant part of my config
```yaml
  ui_end_to_end:
    working_directory: /home/circleci/go/src/github.com/fairwindsops/fairwinds-insights/
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    parallelism: 8
    steps:
      - checkout
      - *add_ssh_keys
      - run: ./.circleci/scripts/env.sh
      - *exit_early_for_wip
      - attach_workspace:
          at: .
      - run: cp -r ./home/circleci/go/src/github.com/fairwindsops/fairwinds-insights/node_modules /home/circleci/go/src/github.com/fairwindsops/fairwinds-insights/node_modules
      - run: ./.circleci/scripts/install-postgres.sh
      - run: ./.circleci/scripts/setup-database.sh
      - run:
          command: ./.circleci/scripts/setup-local-server.sh
          background: true
      - run:
          command: ./.circleci/scripts/e2e-tests.sh
      - persist_to_workspace:
          root: ./
          paths:
          - tests/e2e/snapshots
      - store_artifacts:
          path: tests/e2e/snapshots
      - *notify_slack_on_failure_for_main

```
